name: beautify

on:
  pull_request:
  push:
      
jobs:
  beautify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          # Pass beautysh options in args, for example:
          args: 'routertools --indent-size 4'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[auto] ci: run beautysh'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
